### ISSUE TITLE
wget: not found

### ISSUE THREAD

**Issue by phthom** [blueperf/acmeair-mainservice-java#19]
During the docker build, the wget command is not found. 
Can you please, change your Dockerfile-s for most of your 5 microservices.
Find below the log generated :

Step 1/18 : FROM websphere-liberty:webProfile7
 ---> 6b30f77a8c2b
Step 2/18 : MAINTAINER IBM Java engineering at IBM Cloud
 ---> Using cache
 ---> 27f6aeb4ebcc
Step 3/18 : RUN mkdir -m 777 -p /config/resources
 ---> Using cache
 ---> 03a78dccd165
Step 4/18 : ARG LICENSE_JAR_URL
 ---> Using cache
 ---> d0b1e582934d
Step 5/18 : RUN   if [ $LICENSE_JAR_URL ]; then     wget $LICENSE_JAR_URL -O /tmp/license.jar     && java -jar /tmp/license.jar -acceptLicense /opt/ibm     && rm /tmp/license.jar;   fi
 ---> Using cache
 ---> 4fb8fbe73807
Step 6/18 : ENV JAVA_VERSION_PREFIX 1.8.0
 ---> Using cache
 ---> c3240a4bf786
Step 7/18 : ENV HOME /home/default
 ---> Using cache
 ---> 0b0755305a80
Step 8/18 : RUN set -eux;     ARCH="$(dpkg --print-architecture)";     case "${ARCH}" in        amd64|x86_64)          YML_FILE='sdk/linux/x86_64/index.yml';          ;;        i386)          YML_FILE='sdk/linux/i386/index.yml';          ;;        ppc64el|ppc64le)          YML_FILE='sdk/linux/ppc64le/index.yml';          ;;        s390)          YML_FILE='sdk/linux/s390/index.yml';          ;;        s390x)          YML_FILE='sdk/linux/s390x/index.yml';          ;;        *)          echo "Unsupported arch: ${ARCH}";          exit 1;          ;;     esac;     BASE_URL="https://public.dhe.ibm.com/ibmdl/export/pub/systems/cloud/runtimes/java/meta/";     wget -q -U UA_IBM_JAVA_Docker -O /tmp/index.yml ${BASE_URL}/${YML_FILE};     ESUM=$(cat /tmp/index.yml | sed -n '/'${JAVA_VERSION_PREFIX}'/{n;n;p}' | sed -n 's/\s*sha256sum:\s//p' | tr -d '\r' | tail -1);     JAVA_URL=$(cat /tmp/index.yml | sed -n '/'${JAVA_VERSION_PREFIX}'/{n;p}' | sed -n 's/\s*uri:\s//p' | tr -d '\r' | tail -1);     wget -q -U UA_IBM_JAVA_Docker -O /tmp/ibm-java.bin ${JAVA_URL};     echo "${ESUM}  /tmp/ibm-java.bin" | sha256sum -c -;     echo "INSTALLER_UI=silent" > /tmp/response.properties;     echo "USER_INSTALL_DIR=$HOME/java" >> /tmp/response.properties;     echo "LICENSE_ACCEPTED=TRUE" >> /tmp/response.properties;     mkdir -p $HOME/java;     chmod +x /tmp/ibm-java.bin;     /tmp/ibm-java.bin -i silent -f /tmp/response.properties;     rm -f /tmp/response.properties;     rm -f /tmp/index.yml;     rm -f /tmp/ibm-java.bin;     cd $HOME/java/jre/lib;     rm -rf icc;
 ---> Running in a1a12240e0f9
+ dpkg --print-architecture
+ ARCH=amd64
+ YML_FILE=sdk/linux/x86_64/index.yml
+ BASE_URL=https://public.dhe.ibm.com/ibmdl/export/pub/systems/cloud/runtimes/java/meta/
+ wget -q -U UA_IBM_JAVA_Docker -O /tmp/index.yml https://public.dhe.ibm.com/ibmdl/export/pub/systems/cloud/runtimes/java/meta//sdk/linux/x86_64/index.yml
/bin/sh: 1: wget: not found
The command '/bin/sh -c set -eux;     ARCH="$(dpkg --print-architecture)";     case "${ARCH}" in        amd64|x86_64)          YML_FILE='sdk/linux/x86_64/index.yml';          ;;        i386)          YML_FILE='sdk/linux/i386/index.yml';          ;;        ppc64el|ppc64le)          YML_FILE='sdk/linux/ppc64le/index.yml';          ;;        s390)          YML_FILE='sdk/linux/s390/index.yml';          ;;        s390x)          YML_FILE='sdk/linux/s390x/index.yml';          ;;        *)          echo "Unsupported arch: ${ARCH}";          exit 1;          ;;     esac;     BASE_URL="https://public.dhe.ibm.com/ibmdl/export/pub/systems/cloud/runtimes/java/meta/";     wget -q -U UA_IBM_JAVA_Docker -O /tmp/index.yml ${BASE_URL}/${YML_FILE};     ESUM=$(cat /tmp/index.yml | sed -n '/'${JAVA_VERSION_PREFIX}'/{n;n;p}' | sed -n 's/\s*sha256sum:\s//p' | tr -d '\r' | tail -1);     JAVA_URL=$(cat /tmp/index.yml | sed -n '/'${JAVA_VERSION_PREFIX}'/{n;p}' | sed -n 's/\s*uri:\s//p' | tr -d '\r' | tail -1);     wget -q -U UA_IBM_JAVA_Docker -O /tmp/ibm-java.bin ${JAVA_URL};     echo "${ESUM}  /tmp/ibm-java.bin" | sha256sum -c -;     echo "INSTALLER_UI=silent" > /tmp/response.properties;     echo "USER_INSTALL_DIR=$HOME/java" >> /tmp/response.properties;     echo "LICENSE_ACCEPTED=TRUE" >> /tmp/response.properties;     mkdir -p $HOME/java;     chmod +x /tmp/ibm-java.bin;     /tmp/ibm-java.bin -i silent -f /tmp/response.properties;     rm -f /tmp/response.properties;     rm -f /tmp/index.yml;     rm -f /tmp/ibm-java.bin;     cd $HOME/java/jre/lib;     rm -rf icc;' returned a non-zero code: 127

**Comment by jdmcclur** [comment]
@jagraj is working on this. For now, you can use Dockerfile-base, but it does not have any of the extra microclimate function.

**Comment by jdmcclur** [comment]
Closing because this is the same problem as  https://github.com/blueperf/acmeair-mainservice-java/issues/18.
