### ISSUE TITLE
How to expose Configuration Page externally?

### ISSUE THREAD

**Issue by spitfire88** [blueperf/acmeair-mainservice-java#21]
I am running this app in a GCP cluster. I would like to expose it externally as a service to access its Configuration page. I tried,
> kubectl expose deployment acmeair-mainservice --type=LoadBalancer --name=acmeair-external

It leads me to this webpage on port http://EXTERNAL-IP:9080/
![acme](https://user-images.githubusercontent.com/22776389/63555231-061b6100-c4f5-11e9-947f-8c7cdb8905c0.png)

Is this the expected behaviour?

**Comment by jnativio** [comment]
You should append /acmeair to the URL.

**Comment by spitfire88** [comment]
Thank you, that worked.
