### ISSUE TITLE
Getting connection failure

### ISSUE THREAD

**Issue by igordptx** [blueperf/acmeair-mainservice-java#31]
I have deployed the app with the Istio manifest, in a Minikube local cluster. It is uploaded fine.
When I try access http://minikubeip:nodePort/acmeair I get this error:
"upstream connect error or disconnect/reset before headers. reset reason: connection failure"
When I deploy other apps the same way they seem to work.

**Comment by jdmcclur** [comment]
I'm not sure the Istio manifest works any more. Can you try the normal manifest?
