### ISSUE TITLE
Confusing instructions in README.md

### ISSUE THREAD

**Issue by fmhwong** [blueperf/acmeair-mainservice-java#34]
In this section, most bullet points are for distributed tracing with Jaeger.  Bullet 3 is for enabling logging which has is not related to distributed tracing.

https://github.com/blueperf/acmeair-mainservice-java/blob/master/README.md#addon-openshift-application-tracing-optional

**Comment by jdmcclur** [comment]
@fmhwong 

Hmm good point. I'll move it into a different section.
